#!/bin/csh

#Job name:
#SBATCH --job-name=demo1-bpb3
#
# Project:
#SBATCH --account=nn4605k
#
# Wall clock limit:
#SBATCH --time=12:00:00
#
# Max memory usage:
#SBATCH --mem-per-cpu=20G --partition=bigmem
#
# Number of cores:
#SBATCH --cpus-per-task=12

#run 67 snps demo with PWMs
python bpb3_on_67snps_may22.py



