#!/bin/csh

#Job name:
#SBATCH --job-name=demo7-bpb3_mr
#
# Project:
#SBATCH --account=nn4605k
#
# Wall clock limit:
#SBATCH --time=12:00:00
#
# Max memory usage:
#SBATCH --mem-per-cpu=10G 
##--partition=bigmem
#
# Number of cores:
#SBATCH --cpus-per-task=12



bpb3 run_pipeline --import_bpb3_config bpb3_config_mr_enhancers.py 


